--[[ Colorschemes ]]--

return {
    {
        { "vim/colorschemes"},
        { "jnurmine/Zenburn" },
        { "altercation/vim-colors-solarized" },
        { "danilo-augusto/vim-afterglow" },
        { "rose-pine/neovim", name = "roes-pine" },
        { "catppuccin/nvim", name = "catppuccin" },
        { "morhetz/gruvbox" },
        { "rebelot/kanagawa.nvim" },
        { "folke/tokyonight.nvim" },
        { "webhooked/kanso.nvim" },
        { "bettervim/yugen.nvim" },
        { "navarasu/onedark.nvim" },
        { "bluz71/vim-moonfly-colors", name = "moonfly" },
        { "ribru17/bamboo.nvim" },
        { "edeneast/nightfox.nvim" },
        { "zenbones-theme/zenbones.nvim", dependencies = "rktjmp/lush.nvim"},
        { "biisal/blackhole" },
        { "stevedylandev/darkmatter-nvim" },
        { "tanvirtin/monokai.nvim" },
        { "cooperuser/glowbeam.nvim" },
        { "mitch1000/backpack.nvim" },
        { "p00f/alabaster.nvim" },
        { "darianmorat/gruvdark.nvim" },
        { "wurli/cobalt.nvim" },
        { "makestatic/oblique.nvim" },
        { "WTFox/jellybeans.nvim" },
        { "neanias/everforest-nvim" },
        { "jpwol/thorn.nvim" },
        { "bartekjaszczak/finale-nvim" },
        { "kamwitsta/vinyl.nvim" },
        { "drazil100/dusklight.vim" },
        { "darkvoid-theme/darkvoid.nvim" },
        { "fnune/standard" },
        { "water-sucks/darkrose.nvim" },
        { "uloco/bluloco.nvim" },
    }
}
